### PR TITLE
Add shape_finder implementation

### PR DESCRIPTION
**Pull request by MaximSmolskiy**
### What's new:
* Add `shape_finder` implementation
### Changes:
* Add `shape_finder` code
* Update `README.md` with useful information about `shape_finder` launch

### CODE REVIEW

**Comment by daniilsavchuk** [comment]
IoU score = 0.8 out of 1. Your team now gets 0.8 points.

No circumstances about the code. The code is perfect!

**Review by daniilsavchuk — APPROVED** [review]
Great job!

**Comment by MaximSmolskiy** [comment]
Our group wants to try to improve current result and thus we would like to clarify:
1. Your checker considers the output of the program `shape_finder.py` as `floats` or `ints`? In our `shape_finder.py` we print `floats` in output. Casting `float` to `int` when reading output can reduce the accuracy and, consequently, the IoU metric.
2. Is it guaranteed that in the input file, shape traversal is counterclockwise? This condition is done for all examples.
3. Can image contain a polygon that isn't defined as a shape in input file?

**Comment by daniilsavchuk** [comment]
1. Yes I am casting to Integer according to a task definition (really no matter maybe 1% in maximum, now you have missed objects)

2. It is guaranteed that shape traversed from vertex number **i** to the vertex number **i+1** - always no any other options possible AND shape is always convex

3. Image contains only shapes from the input, not more not less. Every shape from input appears at least once but not limited from the upper boundary. (as a hint current maximum number of the same shape presented in the image is 7 instances). AFAIK your solution is quite good, it fails only with one shape - quite strange case because the same shape in another image goes well, btw I would like to recommend just better revise the algorithm and the code.

**Pull request merged**
